"use strict";
exports.__esModule = true;
var classAra_a_1 = require("./clases/classAra\u00F1a");
var classGato_1 = require("./clases/classGato");
var classPez_1 = require("./clases/classPez");
var classListaDeAnimales_1 = require("./clases/classListaDeAnimales");
var gatito01 = new classGato_1.Gato("Michi01", 5);
var gatito02 = new classGato_1.Gato("Michi02", 4);
var puercoAraña01 = new classAra_a_1.Araña(8);
var puercoAraña02 = new classAra_a_1.Araña(6);
var pezLagarto01 = new classPez_1.Pez("Nemo", 0);
var pezLagarto02 = new classPez_1.Pez("Dory", 0);
var arregloDeAnimales = [gatito01, gatito02, puercoAraña01, puercoAraña02, pezLagarto01];
var nuestrosAnimales = new classListaDeAnimales_1.ListaDeAnimales(arregloDeAnimales);
var resultado = nuestrosAnimales.buscar(pezLagarto02);
console.log("Primera busqueda", resultado);
nuestrosAnimales.agregarAnimal(pezLagarto02);
resultado = nuestrosAnimales.buscar(pezLagarto02);
console.log("Segunda busqueda", resultado);
var consulta = arregloDeAnimales[3].getPatas();
console.log("Consulta devuelve", consulta);
